name: ðŸš€ Deploy Backend to EC2

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: ðŸš€ Deploy Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v4

      - name: ðŸ” Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: ðŸ“¦ Build Docker Image
        run: docker build -t backend-app -f ../docker/backend.Dockerfile .

      - name: ðŸ“¤ Save Image as Tar
        run: docker save backend-app | gzip > backend-app.tar.gz

      - name: ðŸšš Transfer Image to EC2
        run: scp -o StrictHostKeyChecking=no backend-app.tar.gz ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: ðŸš€ Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            docker load < backend-app.tar.gz
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 8080:8080 backend-app
          EOF
